name: test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2


    - name: Build QGIS testing Docker Container
      id: docker-build
      uses: whoan/docker-build-with-cache-action@v5
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        image_name: qgis-test
        dockerfile: .docker/test.Dockerfile
        push_image_and_stages: true

    - name: Run tests
      run: |
        docker run -v $(pwd):/src -w /src/ordered_relation_editor ${DOCKER_IMAGE} pytest
      env:
        DOCKER_IMAGE: ${{ steps.docker-build.outputs.FULL_IMAGE_NAME }}