name: test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install QGIS
      run: |
        cd .docker
        docker build -f test.Dockerfile -t qgis-test .

    - name: Run tests
      run: |
        docker run -v $(pwd):/src -w /src qgis-test pytest