name: test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install QGIS
      run: sudo apt-get update && sudo apt-get install python3-qgis python-nose2

    - name: Run tests
      run: nose2 -v